### ISSUE TITLE
gen_qserver is unable to handle info messages other than AMQP's

### ISSUE THREAD

**Issue by si14** [muxspace/bunny_farm#1]
There is no «fallback» clause in gen_qserver:handle_info, so when gen_qserver receives message, it crashes.

**Comment by muxspace** [comment]
Nice catch. Do you want to make the fix and submit a pull request?

On Mon, Oct 24, 2011 at 12:08 PM, Dmitry Groshev
reply@reply.github.com
wrote:

**Comment by si14** [comment]
Here you go.

**Comment by muxspace** [comment]
Awesome, I'll take a look today and merge.
