### ISSUE TITLE
Queue name option ignored

### ISSUE THREAD

**Issue by DonHub** [muxspace/bunny_farm#16]
Hi,

When creating rabbitmq consumer using notation

```
{{<<"exchange">>,Options}, {<<"route">>,Options}} -- Used for consuming
```

for example:

```
ConnSpecs = [{ {<<"test_exc">>, [{durable, true}]},
               {<<"">>,  [{queue, <<"test_que">>}, {durable, true}, {exclusive, false}]} } ],
gen_qserver:start_link(AppRef, ?MODULE, Args, [], ConnSpecs).
```

I found that in bunny_farm.erl provided queue name is ignored because of empty empty Key. That is idea behind lists:merge? Maybe check for "queue" option existence is needed before merge? 

```
declare_queue(Key, #bus_handle{channel=Channel}, Options) ->
  AllOptions = lists:merge([{queue,Key}], Options),
  QueueDeclare = farm_tools:to_queue_declare(AllOptions),
  #'queue.declare_ok'{queue=Q} = amqp_channel:call(Channel, QueueDeclare),
  Q.
```

If in farm_tools:to_queue_declare instead of "AllOptions" I use "Options" queue is created with provided name.

Thanks in advance
Donatas

**Comment by muxspace** [comment]
Hi, Sorry for the late reply. This change makes sense. Can you submit a pull request with the change integrated?

**Comment by muxspace** [comment]
Thanks for submitting the PR. I merged it.
