### ISSUE TITLE
Official rabbitmq-erlang-client support

### ISSUE THREAD

**Issue by aerosol** [muxspace/bunny_farm#4]
Hi,

The unofficial `gen_bunny`'s `amqp_client` fork is somewhat old; 
`bunny_farm` won't work with current version of the client library: https://github.com/rabbitmq/rabbitmq-erlang-client

**Comment by aerosol** [comment]
I guess this was solved [here](https://github.com/baramiya/bunny_farm/commit/34d87d8ff4c5fe80226872467bb49982363be495)

**Comment by aerosol** [comment]
Hey Brian,

I might have misled you with my suggestion above; I haven't verified this.

Unit tests fail after your merge (#5) . Most likely because there's no `amqp_connection:start/2` any more.

See: https://github.com/jbrisbin/amqp_client/blob/master/src/amqp_connection.erl#L73

**Comment by muxspace** [comment]
Hi,

Sorry I missed this issue. I've created a separate branch for the 2.7.\* support. The mainline is older. Both should build and pass unit tests.

Let me know if you see different behavior.

Brian
